--a
SELECT C_NAME, C_TYPE 
FROM Creature;

--b
SELECT C_NAME 
FROM Creature 
WHERE C_TYPE != 'Person';   

--c
SELECT * 
FROM TOWN 
WHERE T_ID BETWEEN 'b' AND 'g';  

--d
SELECT C_ID, S_DESC
FROM ACHIEVEMENT
JOIN SKILL
ON (SKILL.S_CODE = ACHIEVEMENT.S_CODE);

--e
SELECT C_NAME, S_DESC, SCORE
FROM ACHIEVEMENT
JOIN SKILL
ON (SKILL.S_CODE = ACHIEVEMENT.S_CODE)
JOIN CREATURE
ON (ACHIEVEMENT.C_ID = CREATURE.C_ID);
    
 --f   
SELECT C_NAME, S_DESC, SCORE
FROM ACHIEVEMENT
JOIN CREATURE
ON (CREATURE.C_ID = ACHIEVEMENT.C_ID)
JOIN SKILL
ON (ACHIEVEMENT.S_CODE = SKILL.S_CODE AND ACHIEVEMENT.C_ID = CREATURE.C_ID)
JOIN TOWN
ON (CREATURE.RESIDE_T_ID = TOWN.T_ID)
WHERE (T_NAME = 'Anoka');
    
--g
SELECT J_CODE
FROM JOBSKILL
JOIN SKILL
ON (JOBSKILL.S_CODE = SKILL.S_CODE AND S_DESC = 'Code');


--h
SELECT C_NAME, S_CODE, T_NAME
FROM ASPIRATION
JOIN CREATURE
ON (CREATURE.C_TYPE = 'Person')
JOIN TOWN 
ON(ASPIRATION.TEST_T_ID = TOWN.T_ID)
WHERE CREATURE.C_ID = ASPIRATION.C_ID;

--i
SELECT J_CODE, SKILL.S_CODE
FROM JOB
CROSS JOIN SKILL;


--j
SELECT S_DESC, C_ID
FROM ACHIEVEMENT
RIGHT OUTER JOIN SKILL
ON ACHIEVEMENT.C_ID = ACHIEVEMENT.C_ID AND ACHIEVEMENT.S_CODE = SKILL.S_CODE;