--1
SELECT DISTINCT C.C_NAME, C.C_ID 
FROM CREATURE C 
JOIN ACHIEVEMENT A 
    ON (C.C_ID = A.C_ID) 
JOIN ASPIRATION A2 
    ON (A.C_ID = A2.C_ID) 
WHERE A.S_CODE = A2.S_CODE AND A.SCORE = A2.SCORE;

--2
SELECT A.C_ID, AVG(A.SCORE)
FROM ACHIEVEMENT A
JOIN CREATURE C
    ON A.C_ID = C.C_ID
WHERE C.C_TYPE = 'Person' AND LOWER (C.C_NAME) LIKE '%e%'
GROUP BY A.C_ID;

--2
SELECT A.C_ID, AVG(SCORE)
FROM ACHIEVEMENT A
WHERE C_ID IN (SELECT C_ID 
                FROM CREATURE C
                WHERE C.C_TYPE = 'Person' AND C_NAME LIKE '%e%')
GROUP BY A.C_ID;

--3
SELECT T_NAME, AVG(SCORE)
FROM ACHIEVEMENT A
JOIN TOWN T
    ON (A.TEST_T_ID = T.T_ID)
GROUP BY T.T_NAME;

--4
SELECT A.C_ID, MAX(SCORE)
FROM ACHIEVEMENT A
GROUP BY A.C_ID
ORDER BY A.C_ID;

--5
SELECT C_NAME, C_ID
FROM CREATURE
WHERE C_ID IN(SELECT C_ID
              FROM ACHIEVEMENT OutA
              WHERE S_CODE IN(SELECT S_CODE
                              FROM ACHIEVEMENT InA
                              WHERE C_ID = 1 AND OutA.SCORE >= InA.SCORE AND OutA.C_ID != 1));

--6        
SELECT C_NAME
FROM CREATURE
WHERE C_ID IN(
    SELECT C_ID
    FROM ACHIEVEMENT A1
    WHERE SCORE IN (  
      SELECT MAX(SCORE)
        FROM ACHIEVEMENT A2
        GROUP BY S_CODE
        HAVING A1.S_CODE=A2.S_CODE));


--7
SELECT C.C_ID, C.C_NAME, S_DESC
FROM CREATURE C
JOIN ACHIEVEMENT A 
    ON (C.C_ID = A.C_ID)
JOIN SKILL S 
    ON (A.S_CODE = S.S_CODE)
WHERE C.C_ID IN (SELECT C_ID 
                 FROM ACHIEVEMENT 
                 GROUP BY C_ID 
                 HAVING COUNT(C_ID) >1)
ORDER BY C_ID, S_DESC;

--8
SELECT C_NAME
FROM CREATURE C
WHERE C.C_ID NOT IN (SELECT A.C_ID
                     FROM ACHIEVEMENT A
                     WHERE A.S_CODE IN (SELECT S_CODE
                                        FROM SKILL
                                        WHERE S_DESC = 'Float' ));